/*LOOPCMD.H*/
/*PC EXTENDED KEYBOARD VARIABLES*/
#define END             79
#define F5              63
#define F6              64
/*---------------------------------------*/
/*      COMMANDS FROM THE PC TO THE EVM  */
/*---------------------------------------*/
#define HIGHER          F5   /* RAISE PITCH OF VOICED SOUNDS*/
#define LOWER           F6   /* LOWER PITCH OF VOICED SOUNDS*/
#define QUIT            END  /* EXIT FROM PC CONTROL PROGRAM*/
