/*IIR6BP.C-SIXTH-ORDER IIR FILTER GENERATED BY HYPERSIGNAL
**************************************************************************
* Texas Inst. TMS320C30 C Lang. Filter Realization Copyright (C) by HYPERCEPTION, INC.
**************************************************************************
*
*       Filter Generated from File: IIR6BP.IIR
*
*       Filter Order: M=6;  Number of Sections: N=(M+1)/2=3
*
*       Modified Direct Form II cascade of 2nd order sections:
*
*                N
*             _______              -1        -2
*               | |  { A0i +  A1i z  +  A2i z  }
*       H(z)=   | |   -------------------------- 
*               i=1                -1        -2
*                    {  1  +  B1i z  +  B2i z  }
*
*                    A01                 A02                    A0i
*  x(n) -->- + ----.---- + -->-- + ----.---- + - .... - + ----.---- + -> y(n)
*           /|  z-1|     |\     /|  z-1|     |\        /|  z-1|     |\
*          | |_____v_____| |   | |_____v_____| |      | |_____v_____| |
*          |  -B11 | A11   |   |  -B12 | A12   |      |  -B1i | A1i   |
*          |       |       |   |       |       |      |       |       |
*          |    z-1|       |   |    z-1|       |      |    z-1|       |
*          |_______v_______|   |_______v_______|      |_______v_______|
*             -B21   A21          -B22   A22             -B2i   A2i
*
*
*/
#define NUM_STAGES 3         /* number of 2nd-order stages in filter */

double A[NUM_STAGES][3] = { /* numerator coefficients */
                           {  5.33240103627E-0002,  0.00000000000E+0000, -5.33240103627E-0002 },
                           {  5.33240103627E-0002,  0.00000000000E+0000, -5.33240103627E-0002 },
                           {  5.33240103627E-0002,  0.00000000000E+0000, -5.33240103627E-0002 }
                          };

double B[NUM_STAGES][2] = { /* denominator coefficients */
                           { -1.44351086255E+0000,  9.48796972642E-0001 },
                           { -1.34272159860E+0000,  8.95148059529E-0001 },
                           { -1.30823886588E+0000,  9.43775469012E-0001 }
                          };

double DLY[NUM_STAGES][2];  /* delay storage elements (z-shifts) */

double filt(stage_input)    /* actual filter routine */
double stage_input;
{
    double temp, stage_output;
    int   i;

    for (i=0; i<NUM_STAGES; i++)
    {
        temp = stage_input - B[i][0] * DLY[i][0] - B[i][1] * DLY[i][1];
        stage_output = A[i][0] * temp + A[i][1] * DLY[i][0] + A[i][2] * DLY[i][1];

        DLY[i][1] = DLY[i][0];
        DLY[i][0] = temp;

        stage_input = stage_output;  /* output becomes input for next stage */
    }

    return stage_output;
}

main ()
{
#define IMPULSE_LENGTH 45   /* empirically derived length of impulse response */

volatile int *IO_OUTPUT = (volatile int *) 0x804001;
int   n;

    IO_OUTPUT[0]=filt(0.0);      /* initial zero input for display purposes only */
    IO_OUTPUT[0]=filt(10000.0);  /* the "impulse" input */

    for (n=2; n<IMPULSE_LENGTH; n++)
    {
         IO_OUTPUT[0]=filt(0.0); /* zero input for rest of impulse response length */
    }

}


