/*PROJCMD.H-INTERACTIVE PC COMMANDS DEFINITION */
/*---------------------------------------------*/
/*   PC EXTENDED KEYBOARD VARIABLES            */
/*---------------------------------------------*/
#define F1              59
#define F2              60
#define F3              61
#define F4              62
#define F5              63
#define F6              64
#define F7              65
#define F8              66
#define F9              67
#define F10             68
#define L_ARROW         75
#define R_ARROW         77
#define UP              72  
#define DOWN            80
/*---------------------------------------------*/
/*      COMMANDS FROM THE PC TO THE EVM        */
/*---------------------------------------------*/
#define RESET           F1
#define LPA             F2
#define LPB             F3  
#define LPC             F4                      
#define AVER            F5
#define SEL_RATE        F6
#define EDGE1           F7
#define EDGE2           F8 
#define PAUSE           F9
#define QUIT            F10     
#define L_MINUS         UP
#define L_PLUS          DOWN    
#define SEND            128
#define INCREASE        R_ARROW
#define DECREASE        L_ARROW
